"""empty message

Revision ID: 36c0a058f5c2
Revises: 
Create Date: 2019-06-10 22:04:06.633180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c0a058f5c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paste_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=5000), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('file_md5', sa.String(length=128), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('mime_type', sa.String(length=256), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('file_md5')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('paste_file')
    op.drop_table('login_user')
    # ### end Alembic commands ###
