"""empty message

Revision ID: 53593f1837a3
Revises: 36c0a058f5c2
Create Date: 2019-06-15 16:39:38.748507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53593f1837a3'
down_revision = '36c0a058f5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
